.TH "OLDFILES" 1 "2014/12/05" "Robert L Parker rlp1938@gmail.com"


.SH NAME

.P
\fBoldfiles\fR \- Generate a list of oldfiles to \fIstdout\fR.

.SH SYNOPSIS

.P
\fBoldfiles\fR [option] [head directory].
If not input the default directory is the user's home directory.

.SH DESCRIPTION

.P
\fBoldfiles\fR recurses the head directory and lists old files on
\fIstdout\fR. Errors, including broken symlinks are sent to \fIstderr\fR.

.P
A symlink pointing to an old file will cause both the link and the old
file to be listed even if that target file is outside the search path.
However if a file in the search path is old but it is symlinked from
outside the search path, that symlink will be left dangling if that old
file is deleted.

.P
In typical use, a list of old files would be split into two files, one
for deletion using \fIzapfiles\fR and one to have the file dates renewed
using \fIsetfiletime\fR.

.SH OPTIONS

.TP
 \fB\-h\fR
print help information and exit.

.TP
 \fB\-a N [modifier]\fR
sets the age of old files to be N periods. The modifier is one of d|D
days, m|M months or y|Y years. If no modifier is set the period is
years. If the option is not used the default age is 3 years.

.TP
 \fB\-o yyyymmdd[hh[mm]]\fR
sets the age of the files to select to be the input date.

.SH EXAMPLES

.P
\fIoldfiles\fR ~ > oldies

.P
\fIoldfiles\fR ~ > oldies 2> broken

.SH SEE ALSO

.P
\fBbigfiles\fR(1), \fBbrokebsym\fR(1), \fBduplicates\fR(1),
\fBdelemptydir\fR(1), \fBprocessdups\fR(1), \fBsetfiletime\fR(1),
\fBzapfiles\fR(1), for a brief overview see \fBcleanuputils\fR(1).

.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags -t man oldfiles.t2t
