.TH OLDFILES 1 "v\ 1.1.0" "2014-0-18" "GNU"
.SH NAME
.B oldfiles
\- Generate a list of oldfiles in optional user input dir.
.br
Oldfiles are listed on stdout and broken symlinks on stderr.
.SH SYNOPSIS
.B duplicates \fR[option] \fI[dir]\fR > \fIoldfiles\fR
.br
.B duplicates \fR[option] \fI[dir]\fR > \fIoldfiles\fR 2> \fIbroken\fR
.SH OPTIONS
.TP
\-h, prints a brief help message.
.TP
\-a N[MmDdYy], choose file age. By default this is 3 years older than
.br
the time of program execution. The qualifier [MmDdYy] represents
.br
months, days or years. If not specified the default is years.

.TP
\-o yyyymmdd[hh[mm]], list files older than this date.
.SH DESCRIPTION
\fBoldfiles\fR recursively searches the user input dir, or in default
.br
the users home dir, and generates a list of files older than the
.br
optional input age or input cutoff date. By default the cutoff date
.br
is 3 years older than the time the program is run.
.br
Broken symlinks are sent to \fIstderr\fR when encountered.
.br
Symlinked files, if old, will cause both the symlink and the linked
.br
file to be listed. This applies even if the linked file is outside
.br
the search path. On the other hand, an old file which is linked by
.br
a symlink outside the search path will leave that link dangling when
.br
it's target is deleted.
.SH VERSION
This documentation describes \fBolsfiles\fR version 1.1.0
.SH "SEE ALSO"
bigfiles(1), brokensym(1), duplicates(1), filetimes(1, )processdups(1), zapfiles(1), cleanuputils(7)
